# Generated by Django 6.0.4 on 2026-04-19 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_fisico', models.CharField(choices=[('OK', 'OK'), ('CANSADO', 'CANSADO'), ('DOLOR', 'DOLOR'), ('CRITICO', 'CRITICO')], max_length=20)),
                ('estado_emocional', models.CharField(default='NEUTRO', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='mi_app_salud.paciente')),
            ],
        ),
    ]
