# Generated by Django 6.0.4 on 2026-04-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0002_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
