# Generated by Django 6.0.4 on 2026-04-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0003_alter_recordatorio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosalud',
            name='estado',
            field=models.CharField(default='OK', max_length=20),
        ),
    ]
