# Generated by Django 6.0.4 on 2026-07-28 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0005_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tomada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='mi_app_salud.paciente')),
            ],
        ),
    ]
