# Generated by Django 6.0.4 on 2026-07-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0006_medicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='medicacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='medicacion',
            name='tomada',
        ),
        migrations.AddField(
            model_name='medicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='dosis',
            field=models.CharField(max_length=50),
        ),
    ]
