# Generated by Django 6.0.4 on 2026-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0007_remove_medicacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacion',
            name='fecha_toma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='tomado',
            field=models.BooleanField(default=False),
        ),
    ]
