# Generated by Django 6.0.4 on 2026-07-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0008_medicacion_fecha_toma_medicacion_tomado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicacion',
            name='fecha_toma',
        ),
    ]
