# Generated by Django 6.0.4 on 2026-07-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0010_medicacion_confirmado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalud',
            name='estado_fisico',
            field=models.CharField(choices=[('OK', 'OK'), ('CANSADO', 'CANSADO'), ('DOLOR', 'DOLOR'), ('CRITICO', 'CRITICO')], default='OK', max_length=20),
        ),
    ]
