# Generated by Django 6.0.4 on 2026-07-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0011_alter_registrosalud_estado_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
