# Generated by Django 6.0.4 on 2026-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mi_app_salud",
            "0012_perfilusuario_apellido_perfilusuario_especialidad_and_more"
        ),
    ]

    operations = [

        migrations.AddField(
            model_name="paciente",
            name="alergias",
            field=models.TextField(blank=True),
        ),

        migrations.AddField(
            model_name="paciente",
            name="altura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="contacto_emergencia",
            field=models.CharField(
                blank=True,
                max_length=150
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="direccion",
            field=models.TextField(
                blank=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="dni",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="enfermedades",
            field=models.TextField(
                blank=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True,
                null=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="grupo_sanguineo",
            field=models.CharField(
                blank=True,
                max_length=5
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="medico_cabecera",
            field=models.CharField(
                blank=True,
                max_length=150
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="observaciones",
            field=models.TextField(
                blank=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Femenino"),
                    ("M", "Masculino"),
                    ("O", "Otro"),
                ],
                max_length=1
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=30
            ),
        ),

        migrations.AddField(
            model_name="paciente",
            name="telefono_emergencia",
            field=models.CharField(
                blank=True,
                max_length=30
            ),
        ),

        migrations.AlterField(
            model_name="paciente",
            name="apellido",
            field=models.CharField(
                default="Sin apellido",
                max_length=100
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name="paciente",
            name="edad",
            field=models.PositiveIntegerField(
                default=0
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("MEDICO", "Médico"),
                    ("ENFERMERIA", "Enfermería"),
                    ("PACIENTE", "Paciente"),
                    ("FAMILIAR", "Familiar"),
                    ("EMERGENCIA", "Emergencias"),
                ],
                default="PACIENTE",
                max_length=20,
            ),
        ),
    ]