# Generated by Django 6.0.4 on 2026-08-03 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0014_alter_paciente_fecha_creacion_evolucionmedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='mi_app_salud.paciente')),
            ],
        ),
    ]
