# Generated by Django 6.0.4 on 2026-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0016_evolucionmedica_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiomedico',
            name='institucion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estudiomedico',
            name='profesional',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
