# Generated by Django 6.0.4 on 2026-08-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0018_solicitudestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudestudio',
            name='archivo_informe',
            field=models.FileField(blank=True, null=True, upload_to='estudios/'),
        ),
        migrations.AddField(
            model_name='solicitudestudio',
            name='fecha_realizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudestudio',
            name='informe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('ENFERMERIA', 'Enfermería'), ('PACIENTE', 'Paciente'), ('FAMILIAR', 'Familiar'), ('EMERGENCIA', 'Emergencias'), ('INSTITUCION', 'Institución')], default='PACIENTE', max_length=20),
        ),
    ]
