# Generated by Django 6.0.4 on 2026-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0019_solicitudestudio_archivo_informe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historia_clinica',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
