# Generated by Django 6.0.4 on 2026-08-11 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0020_paciente_historia_clinica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaJarvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('ACTIVAR', 'Activación'), ('DESACTIVAR', 'Desactivación'), ('EMERGENCIA', 'Emergencia'), ('SEGURIDAD', 'Seguridad'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('modulo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_jarvice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
