# Generated by Django 6.0.4 on 2026-08-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0022_paciente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20)),
                ('estado_emocional', models.CharField(blank=True, max_length=50)),
                ('origen', models.CharField(choices=[('MANUAL', 'Carga manual'), ('SMARTWATCH', 'Smartwatch'), ('SENSOR', 'Sensor'), ('SISTEMA', 'Sistema')], default='MANUAL', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='mi_app_salud.paciente')),
            ],
        ),
    ]
