# Generated by Django 6.0.4 on 2026-08-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0024_accesoclinico_qrtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia_3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_emergencia_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_emergencia_3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='accesoclinico',
            name='tipo_acceso',
            field=models.CharField(choices=[('ENFERMERIA', 'EnfermerÃ\xada'), ('MEDICO', 'MÃ©dico'), ('EMERGENCIA', 'Emergencia'), ('ADMIN', 'Administrador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriajarvice',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesiÃ³n'), ('LOGOUT', 'Cierre de sesiÃ³n'), ('CREAR', 'CreaciÃ³n'), ('MODIFICAR', 'ModificaciÃ³n'), ('ELIMINAR', 'EliminaciÃ³n'), ('ACTIVAR', 'ActivaciÃ³n'), ('DESACTIVAR', 'DesactivaciÃ³n'), ('EMERGENCIA', 'Emergencia'), ('SEGURIDAD', 'Seguridad'), ('SISTEMA', 'Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'MÃ©dico'), ('ENFERMERIA', 'EnfermerÃ\xada'), ('PACIENTE', 'Paciente'), ('FAMILIAR', 'Familiar'), ('EMERGENCIA', 'Emergencias'), ('INSTITUCION', 'InstituciÃ³n')], default='PACIENTE', max_length=20),
        ),
    ]
