# Generated by Django 6.0.4 on 2026-08-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0025_paciente_contacto_emergencia_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SMARTWATCH', 'Smartwatch'), ('SENSOR', 'Sensor')], default='SMARTWATCH', max_length=20)),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('conectado', models.BooleanField(default=False)),
                ('bateria', models.PositiveIntegerField(default=100)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='mi_app_salud.paciente')),
            ],
        ),
    ]
