# Generated by Django 6.0.4 on 2026-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0026_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoclinico',
            name='tipo_acceso',
            field=models.CharField(choices=[('ENFERMERIA', 'Enfermería'), ('MEDICO', 'Médico'), ('EMERGENCIA', 'Emergencia'), ('ADMIN', 'Administrador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriajarvice',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('ACTIVAR', 'Activación'), ('DESACTIVAR', 'Desactivación'), ('EMERGENCIA', 'Emergencia'), ('SEGURIDAD', 'Seguridad'), ('SISTEMA', 'Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('ENFERMERIA', 'Enfermería'), ('PACIENTE', 'Paciente'), ('FAMILIAR', 'Familiar'), ('EMERGENCIA', 'Emergencias'), ('INSTITUCION', 'Institución')], default='PACIENTE', max_length=20),
        ),
    ]
