# Generated by Django 6.0.4 on 2026-09-02 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0027_alter_accesoclinico_tipo_acceso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucionEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ESTABLE', 'Estable'), ('OBSERVACION', 'En observación'), ('DOLOR', 'Dolor'), ('CRITICO', 'Crítico')], default='ESTABLE', max_length=20)),
                ('observaciones', models.TextField()),
                ('intervenciones', models.TextField(blank=True)),
                ('incidentes', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones_enfermeria', to='mi_app_salud.paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones_enfermeria_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
