# Generated by Django 6.0.4 on 2026-09-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0028_evolucionenfermeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='enfermera_asignada',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ENFERMERIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to='mi_app_salud.perfilusuario'),
        ),
    ]
