# Generated by Django 6.0.4 on 2026-09-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0029_paciente_enfermera_asignada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUGERENCIA', 'Sugerencia'), ('OPINION', 'Opinión'), ('PROBLEMA', 'Problema técnico'), ('RECLAMO', 'Queja / Reclamo'), ('ATENCION', 'Atención al usuario')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISION', 'En revisión'), ('RESPONDIDO', 'Respondido'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_jarvice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
