# Generated by Django 6.0.4 on 2026-09-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0030_solicitudusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='credencial_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
