# Generated by Django 6.0.4 on 2026-09-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0031_dispositivo_credencial_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_salud_mental',
            field=models.TextField(blank=True),
        ),
    ]
