# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app_salud", "0032_paciente_antecedentes_salud_mental"),
    ]

    operations = [
        migrations.AddField(
            model_name="signovital",
            name="latitud",
            field=models.DecimalField(
                max_digits=9,
                decimal_places=6,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="signovital",
            name="longitud",
            field=models.DecimalField(
                max_digits=9,
                decimal_places=6,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="signovital",
            name="fecha_ubicacion",
            field=models.DateTimeField(
                null=True,
                blank=True,
            ),
        ),
    ]