# Generated by Django 6.0.4 on 2026-09-15 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0033_remove_signovital_fecha_signovital_latitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosalud',
            name='signo_vital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='mi_app_salud.signovital'),
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='tipo_alerta',
            field=models.CharField(choices=[('ESTADO', 'Cambio de estado'), ('SIGNOS_VITALES', 'Signos vitales')], default='ESTADO', max_length=30),
        ),
    ]
