# Generated by Django 6.0.4 on 2026-09-16 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0034_registrosalud_signo_vital_registrosalud_tipo_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoclinico',
            name='qr_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='mi_app_salud.qrtoken'),
        ),
    ]
