# Generated by Django 6.0.4 on 2026-09-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0035_accesoclinico_qr_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracionMedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ADMINISTRADO', 'Administrado'), ('NO_ADMINISTRADO', 'No administrado'), ('OMITIDO', 'Omitido')], default='ADMINISTRADO', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('administrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administraciones_medicacion', to=settings.AUTH_USER_MODEL)),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administraciones', to='mi_app_salud.medicacion')),
            ],
        ),
    ]
