# Generated by Django 6.0.4 on 2026-09-16 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0036_administracionmedicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacion',
            name='fecha_indicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='indicaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_indicados', to=settings.AUTH_USER_MODEL),
        ),
    ]
