# Generated by Django 6.0.4 on 2026-09-19 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0037_medicacion_fecha_indicacion_medicacion_indicaciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergenciaJarvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DETECTADA', 'Detectada'), ('ALERTADA', 'Alertada'), ('OPERADOR', 'Operador conectado'), ('UNIDAD_EN_CAMINO', 'Unidad en camino'), ('ASISTIDA', 'Paciente asistido'), ('CERRADA', 'Emergencia cerrada')], default='DETECTADA', max_length=30)),
                ('origen', models.CharField(default='SMARTWATCH', max_length=30)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_operadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencias_jarvice', to='mi_app_salud.paciente')),
                ('registro_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias', to='mi_app_salud.registrosalud')),
                ('signo_vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias', to='mi_app_salud.signovital')),
            ],
        ),
    ]
