# Generated by Django 6.0.4 on 2026-09-20 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_salud', '0038_emergenciajarvice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INACTIVA', 'Inactiva'), ('CONECTANDO', 'Conectando'), ('ACTIVA', 'Comunicación activa'), ('FINALIZADA', 'Comunicación finalizada')], default='INACTIVA', max_length=20)),
                ('canal', models.CharField(default='RADIO', max_length=30)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('emergencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacion', to='mi_app_salud.emergenciajarvice')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_emergencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
