# Generated by Django 6.0.4 on 2026-04-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalud',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
