# Generated by Django 6.0.4 on 2026-04-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0002_alter_registrosalud_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosalud',
            name='tomo_medicacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrosalud',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='salud.paciente'),
        ),
    ]
