# Generated by Django 6.0.4 on 2026-04-17 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0003_registrosalud_tomo_medicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalud',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='registrosalud',
            name='presion_arterial',
        ),
        migrations.RemoveField(
            model_name='registrosalud',
            name='tomo_medicacion',
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='estado',
            field=models.CharField(default='OK', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='medicacion_tomada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registrosalud',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente'),
        ),
    ]
