# Generated by Django 6.0.4 on 2026-04-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0004_remove_registrosalud_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalud',
            name='medicacion_tomada',
        ),
        migrations.AlterField(
            model_name='registrosalud',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='salud.paciente'),
        ),
    ]
