# Generated by Django 6.0.4 on 2026-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0005_remove_registrosalud_medicacion_tomada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalud',
            name='estado',
            field=models.CharField(choices=[('OK', 'Normal'), ('CANSADO', 'Cansado'), ('DOLOR', 'Dolor'), ('CRITICO', 'Crítico')], max_length=20),
        ),
    ]
