# Generated by Django 6.0.4 on 2026-04-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0006_alter_registrosalud_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalud',
            name='estado',
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='estado_emocional',
            field=models.CharField(choices=[('BAJO', 'Calma'), ('MEDIO', 'Estrés medio'), ('ALTO', 'Ansiedad alta')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='estado_fisico',
            field=models.CharField(choices=[('OK', 'Normal'), ('DOLOR', 'Dolor'), ('CRITICO', 'Crítico')], default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
