# Generated by Django 6.0.4 on 2026-04-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0007_remove_registrosalud_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalud',
            name='estado_emocional',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrosalud',
            name='estado_fisico',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
    ]
