# Generated by Django 6.0.4 on 2026-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0008_alter_registrosalud_estado_emocional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalud',
            name='estado_fisico',
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='medicacion_tomada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='presion_diastolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='presion_sistolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosalud',
            name='estado_emocional',
            field=models.CharField(choices=[('OK', 'Normal'), ('ESTRES', 'Estrés'), ('ANSIEDAD', 'Ansiedad'), ('PANICO', 'Pánico')], default='OK', max_length=20),
        ),
    ]
