# Generated by Django 6.0.4 on 2026-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0009_remove_registrosalud_estado_fisico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalud',
            name='estado_emocional',
        ),
        migrations.RemoveField(
            model_name='registrosalud',
            name='frecuencia_cardiaca',
        ),
        migrations.RemoveField(
            model_name='registrosalud',
            name='medicacion_tomada',
        ),
        migrations.RemoveField(
            model_name='registrosalud',
            name='presion_diastolica',
        ),
        migrations.RemoveField(
            model_name='registrosalud',
            name='presion_sistolica',
        ),
        migrations.RemoveField(
            model_name='registrosalud',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='estado',
            field=models.CharField(choices=[('OK', 'Normal'), ('CANSADO', 'Cansado'), ('DOLOR', 'Dolor'), ('CRITICO', 'Crítico')], default='OK', max_length=20),
        ),
    ]
