# Generated by Django 6.0.4 on 2026-04-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0010_remove_registrosalud_estado_emocional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalud',
            name='estado',
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='estado_emocional',
            field=models.CharField(choices=[('CALMA', 'Calma'), ('ANSIEDAD', 'Ansiedad'), ('ESTRES', 'Estrés'), ('TRISTEZA', 'Tristeza')], default='CALMA', max_length=20),
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='estado_fisico',
            field=models.CharField(choices=[('ENERGIA', 'Energía'), ('CANSADO', 'Cansado'), ('DOLOR', 'Dolor'), ('CRITICO', 'Crítico')], default='ENERGIA', max_length=20),
        ),
    ]
